const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE_KEY='ecolink_zambeze_v3';
const POINT_RATE=0.05;
const DEMO_USERS={
  admin:{role:'admin',name:'Administrador',phone:'+258 84 123 4567',password:'12345678',label:'Administrador'},
  municipe:{role:'municipe',name:'João',phone:'+258 85 222 3344',password:'12345678',label:'Munícipe'},
  reciclador:{role:'reciclador',name:'Carlos Reciclador',phone:'+258 86 333 4455',password:'12345678',label:'Reciclador'}
};
const seed={
  users:[{id:'U001',name:'João',phone:'+258 85 222 3344',role:'municipe',points:125,status:'Ativo',bairro:'Centro'}, {id:'U002',name:'Maria da Silva',phone:'+258 84 111 2233',role:'municipe',points:125,status:'Ativo',bairro:'Centro'}],
  recyclers:[{id:'R001',name:'Carlos Reciclador',phone:'+258 86 333 4455',zone:'Centro',status:'Online',collections:12}],
  requests:[],payouts:[],reports:[],rewards:[]
};
function cloneSeed(){return JSON.parse(JSON.stringify(seed))}
function load(){try{return {...cloneSeed(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return cloneSeed()}}
let state=load(); let session=null;
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]));}
function toast(message,type='success'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toast-container').appendChild(el);setTimeout(()=>el.remove(),3200)}
function roleName(r){return r==='admin'?'Administrador':r==='reciclador'?'Reciclador':'Munícipe'}
const pageMeta={dashboard:['Dashboard','Visão geral da plataforma EcoLink'],citizen:['Portal do Munícipe','Reporte resíduos, acompanhe pedidos e pontos'],recycler:['Painel do Reciclador','Pedidos atribuídos, recolhas e materiais'],requests:['Solicitações','Gestão dos pedidos de recolha'],users:['Utilizadores','Munícipes e contas registadas'],recyclers:['Recicladores','Equipas responsáveis pelas recolhas'],pickups:['Recolhas','Monitorização das recolhas'],points:['Pontos de Reciclagem','Locais de entrega de materiais'],rewards:['Recompensas','Pontos e levantamentos M-Pesa/e-Mola'],reports:['Relatórios','Indicadores ambientais e operacionais'],settings:['Configurações','Definições da plataforma']};
const permissions={admin:['dashboard','requests','users','recyclers','pickups','points','reports','settings'],municipe:['citizen','points','rewards'],reciclador:['recycler','requests','pickups','points']};
function showPage(name){if(!session||!permissions[session.role].includes(name)){toast('Não tem permissão para aceder a este módulo.','error');return} $$('.page').forEach(p=>p.classList.remove('active'));$(`#page-${name}`)?.classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===name));if(pageMeta[name]){$('#page-title').textContent=pageMeta[name][0];$('#page-subtitle').textContent=pageMeta[name][1]}$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});renderAll()}
function setupRoleNav(){ $$('.nav-item').forEach(n=>{n.style.display=session&&permissions[session.role].includes(n.dataset.page)?'flex':'none'}); }
function setSession(u){session={...u};session.points=getUser().points;$('#login-screen').classList.add('hidden');$('#app').classList.remove('hidden');$('#profile-name').textContent=roleName(session.role);$('#profile-sub').textContent=session.name;$('#avatar').textContent=session.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();setupRoleNav();showPage(session.role==='admin'?'dashboard':session.role==='reciclador'?'recycler':'citizen');toast(`Bem-vindo, ${session.name}!`)}
function getUser(){let u=state.users.find(x=>x.phone.replace(/\D/g,'')===session.phone.replace(/\D/g,''));if(!u){u={id:'U'+Date.now(),name:session.name,phone:session.phone,role:session.role,points:0,status:'Ativo',bairro:'Centro'};state.users.push(u);save()}return u}
function logout(){session=null;$('#app').classList.add('hidden');$('#login-screen').classList.remove('hidden');$('#login-form').reset();toast('Sessão terminada.')}
$('#login-role').addEventListener('change',()=>{$('#phone').value=DEMO_USERS[$('#login-role').value].phone});
$('#login-form').addEventListener('submit',e=>{e.preventDefault();const role=$('#login-role').value,phone=$('#phone').value.trim(),pass=$('#password').value;if(pass!=='12345678'){toast('Palavra-passe de demonstração: 12345678','error');return}const d=DEMO_USERS[role];setSession({...d,phone:phone||d.phone})});
$('#logout').addEventListener('click',logout);$('#toggle-password').addEventListener('click',()=>{const p=$('#password');p.type=p.type==='password'?'text':'password'});$('#forgot-password').addEventListener('click',e=>{e.preventDefault();toast('Modo local: use a palavra-passe 12345678.')});$('#register-demo').addEventListener('click',()=>openRegistration());$('#mobile-menu').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#notifications').addEventListener('click',()=>toast('Notificações: pedidos, recolhas e recompensas.'));
document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item,[data-go]');if(nav){e.preventDefault();showPage(nav.dataset.page||nav.dataset.go)}});
function openModal(title,content){$('#modal-title').textContent=title;$('#modal-content').innerHTML=content;$('#modal').classList.remove('hidden')}
$('#modal-close').addEventListener('click',()=>$('#modal').classList.add('hidden'));$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')});
function openRegistration(){openModal('Criar conta',`<form id="register-form" class="modal-form"><label>Nome<input id="reg-name" required></label><label>Telefone<input id="reg-phone" required placeholder="+258 84 123 4567"></label><label>Tipo de conta<select id="reg-role"><option value="municipe">Munícipe</option><option value="reciclador">Reciclador</option></select></label><label>Palavra-passe<input id="reg-pass" type="password" value="12345678" required></label><button class="btn btn-primary btn-full">Criar conta</button></form>`);$('#register-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#reg-name').value.trim(),phone=$('#reg-phone').value.trim(),role=$('#reg-role').value;if(state.users.some(u=>u.phone===phone)){toast('Este telefone já está registado.','error');return}const u={id:'U'+Date.now(),name,phone,role,points:0,status:'Ativo',bairro:'Centro'};state.users.push(u);if(role==='reciclador')state.recyclers.push({id:'R'+Date.now(),name,phone,zone:'Centro',status:'Online',collections:0});save();$('#modal').classList.add('hidden');setSession({...u,password:'12345678'});toast('Conta criada com sucesso.')})}
function statusClass(s){return s==='Concluído'?'done':s==='Em andamento'?'progress':'pending'}
function allRequests(){return state.requests}
function renderRequests(){const tbody=$('#requests-table tbody');if(!tbody)return;const existing=[...tbody.querySelectorAll('[data-local-id]')].map(x=>x.dataset.localId);state.requests.forEach(r=>{if(existing.includes(String(r.id)))return;const tr=document.createElement('tr');tr.dataset.localId=r.id;tr.innerHTML=`<td>${esc(r.id)}</td><td><strong>${esc(r.user)}</strong></td><td>${esc(r.type)}</td><td>${esc(r.quantity)}</td><td>${esc(r.address)}</td><td><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></td><td>${esc(r.date)}</td><td><button class="row-action" data-request="${esc(r.id)}">⋮</button></td>`;tbody.prepend(tr)});filterRequests()}
function filterRequests(){const q=$('#request-search')?.value.toLowerCase()||'',st=$('#status-filter')?.value||'Todas',type=$('#type-filter')?.value||'Todos os resíduos';let visible=0;$$('#requests-table tbody tr').forEach(row=>{const cells=row.children,text=row.innerText.toLowerCase(),status=cells[5]?.innerText||'',typ=cells[2]?.innerText||'';const ok=(!q||text.includes(q))&&(st==='Todas'||status===st)&&(type==='Todos os resíduos'||typ===type);row.style.display=ok?'':'none';if(ok)visible++});if($('#table-count'))$('#table-count').textContent=`Mostrando ${visible} entradas locais`}
$('#request-search')?.addEventListener('input',filterRequests);$('#status-filter')?.addEventListener('change',filterRequests);$('#type-filter')?.addEventListener('change',filterRequests);
function openRequest(id){const r=state.requests.find(x=>String(x.id)===String(id));if(!r)return;let actions='';if(session.role==='admin'){actions=`<label>Reciclador responsável<select id="assign-recycler"><option value="">Por atribuir</option>${state.recyclers.map(x=>`<option ${r.recycler===x.name?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div class="quick-actions"><button class="btn btn-primary" data-assign-request="${r.id}">Guardar atribuição</button><button class="btn btn-outline" data-request-status="Concluído" data-id="${r.id}">Marcar concluído</button></div>`}else if(session.role==='reciclador'){actions=`<div class="quick-actions"><button class="btn btn-primary" data-request-status="Em andamento" data-id="${r.id}">Aceitar / iniciar</button><button class="btn btn-outline" data-request-status="Concluído" data-id="${r.id}">Marcar concluído</button></div>`}openModal(`Solicitação ${r.id}`,`<div class="detail-grid"><div class="detail"><small>Munícipe</small><strong>${esc(r.user)}</strong></div><div class="detail"><small>Resíduo</small><strong>${esc(r.type)}</strong></div><div class="detail"><small>Quantidade</small><strong>${esc(r.quantity)}</strong></div><div class="detail"><small>Endereço</small><strong>${esc(r.address)}</strong></div><div class="detail"><small>Status</small><strong>${esc(r.status)}</strong></div><div class="detail"><small>Reciclador</small><strong>${esc(r.recycler||'Por atribuir')}</strong></div></div>${r.photos?.length?`<div class="modal-photos">${r.photos.map(p=>`<img src="${p}" alt="Foto do resíduo">`).join('')}</div>`:''}${actions}`)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-request]');if(b)openRequest(b.dataset.request);const ab=e.target.closest('[data-assign-request]');if(ab){const r=state.requests.find(x=>String(x.id)===ab.dataset.assignRequest);if(r){r.recycler=$('#assign-recycler').value||'';if(r.recycler&&r.status==='Pendente')r.status='Em andamento';save();$('#modal').classList.add('hidden');renderAll();toast('Pedido atribuído ao reciclador.')}}const sb=e.target.closest('[data-request-status]');if(sb){const r=state.requests.find(x=>String(x.id)===sb.dataset.id);if(r){r.status=sb.dataset.requestStatus;if(r.status==='Em andamento'&&session.role==='reciclador')r.recycler=session.name;if(r.status==='Concluído'){r.recycler=r.recycler||session.name;r.completedAt=new Date().toLocaleString('pt-MZ')}save();$('#modal').classList.add('hidden');renderAll();toast(`Solicitação ${r.id}: ${r.status}.`)}}});
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1000,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
let selectedFiles=[];const camera=$('#report-camera'),gallery=$('#report-gallery');function showPhotos(){const box=$('#photo-preview');box.innerHTML='';selectedFiles.slice(0,5).forEach((f,i)=>{const div=document.createElement('div');div.className='photo-item';div.innerHTML=`<img alt="Foto ${i+1}"><button type="button" data-remove-photo="${i}">×</button>`;const r=new FileReader();r.onload=()=>div.querySelector('img').src=r.result;r.readAsDataURL(f);box.appendChild(div)})}
$('#open-camera')?.addEventListener('click',()=>camera.click());$('#open-gallery')?.addEventListener('click',()=>gallery.click());camera?.addEventListener('change',e=>{selectedFiles=[...selectedFiles,...e.target.files].slice(0,5);showPhotos()});gallery?.addEventListener('change',e=>{selectedFiles=[...selectedFiles,...e.target.files].slice(0,5);showPhotos()});document.addEventListener('click',e=>{const b=e.target.closest('[data-remove-photo]');if(b){selectedFiles.splice(Number(b.dataset.removePhoto),1);showPhotos()}});
$('#pickup-form')?.addEventListener('submit',e=>{e.preventDefault();if(session?.role!=='municipe'){toast('Apenas munícipes podem solicitar recolhas.','error');return}const r={id:'#'+(1000+state.requests.length+1),user:session.name,type:$('#pickup-type').value,quantity:'A pedido',address:$('#pickup-address').value.trim(),note:$('#pickup-note').value.trim(),date:new Date().toLocaleDateString('pt-MZ'),status:'Pendente',photos:[],reward:0};state.requests.push(r);save();$('#pickup-form').reset();renderAll();toast(`Pedido ${r.id} enviado ao EcoLink.`)});
$('#report-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!session||session.role!=='municipe'){toast('Apenas munícipes podem criar este reporte.','error');return}if(!selectedFiles.length){toast('Adicione pelo menos uma fotografia.','error');return}const photos=await Promise.all(selectedFiles.map(compressImage));const id='#'+(1000+state.requests.length+1);const r={id,user:session.name,type:$('#report-type').value,quantity:$('#report-quantity').value,address:$('#report-address').value.trim(),note:$('#report-note').value.trim(),date:new Date().toLocaleDateString('pt-MZ'),status:'Pendente',photos,reward:10};state.requests.push(r);state.reports.push(r);const u=getUser();u.points+=10;save();selectedFiles=[];camera.value='';gallery.value='';$('#report-form').reset();showPhotos();renderAll();toast(`Reporte ${id} enviado. +10 pontos.`)});
$('#locate-report')?.addEventListener('click',()=>{if(!navigator.geolocation){toast('Geolocalização não suportada.','error');return}navigator.geolocation.getCurrentPosition(p=>{$('#report-address').value=`Lat ${p.coords.latitude.toFixed(5)}, Lon ${p.coords.longitude.toFixed(5)}`;toast('Localização obtida.')},()=>toast('Não foi possível obter a localização.','error'),{enableHighAccuracy:true,timeout:10000})});
function renderCitizen(){const u=getUser();if($('#citizen-points'))$('#citizen-points').textContent=u.points;if($('#citizen-money'))$('#citizen-money').textContent=(u.points*POINT_RATE).toFixed(2)+' MT';const box=$('#citizen-history');if(box)box.innerHTML=state.requests.filter(r=>r.user===session.name).slice().reverse().map(r=>`<div class="history-row"><strong>${esc(r.id)}</strong><span>${esc(r.type)} · ${esc(r.address)}</span><em class="status ${statusClass(r.status)}">${esc(r.status)}</em></div>`).join('')||'<p class="empty-state">Ainda não existem reportes.</p>'}
function renderRecycler(){const mine=state.requests.filter(r=>r.recycler===session?.name||(r.status==='Pendente'&&session?.role==='reciclador'));const box=$('#recycler-requests');if(box)box.innerHTML=mine.map(r=>`<div class="task-card"><div><strong>${esc(r.id)} · ${esc(r.type)}</strong><p>${esc(r.address)} · ${esc(r.quantity)}</p></div><span class="status ${statusClass(r.status)}">${esc(r.status)}</span><button class="btn btn-outline" data-request="${r.id}">Ver</button></div>`).join('')||'<p class="empty-state">Nenhuma solicitação disponível.</p>';if($('#recycler-count'))$('#recycler-count').textContent=mine.length}
function renderRewards(){const u=getUser();if($('#reward-points'))$('#reward-points').textContent=u.points;if($('#reward-money'))$('#reward-money').textContent=(u.points*POINT_RATE).toFixed(2)+' MT';const list=$('#payout-history');if(list)list.innerHTML=state.payouts.filter(p=>p.phone===session.phone).slice().reverse().map(p=>`<div class="payout-item"><div><strong>${esc(p.method)}</strong><small>${esc(p.phone)} · ${esc(p.date)}</small></div><b>${p.amount.toFixed(2)} MT</b><span class="status done">Simulado</span></div>`).join('')||'<p class="empty-state">Ainda não existem levantamentos.</p>'}
$('#redeem-points')?.addEventListener('input',e=>$('#payout-preview').textContent=((Number(e.target.value)||0)*POINT_RATE).toFixed(2)+' MT');$('#payout-form')?.addEventListener('submit',e=>{e.preventDefault();const pts=Number($('#redeem-points').value),method=$('#payout-method').value,phone=$('#payout-phone').value.trim();const u=getUser();if(!Number.isInteger(pts)||pts<100||pts%100){toast('Use múltiplos de 100 pontos.','error');return}if(pts>u.points){toast('Saldo insuficiente.','error');return}if(!/^258\d{9}$/.test(phone.replace(/\D/g,''))){toast('Número moçambicano inválido.','error');return}u.points-=pts;state.payouts.push({points:pts,amount:pts*POINT_RATE,method,phone,date:new Date().toLocaleString('pt-MZ')});save();renderRewards();renderCitizen();toast(`${(pts*POINT_RATE).toFixed(2)} MT preparados para ${method}. (modo demonstração)`)});
function renderStats(){const req=state.requests;const totalUsers=state.users.length+1250,totalReq=req.length+342,totalPick=req.filter(r=>r.status==='Concluído').length+289;$$('[data-stat="users"]').forEach(x=>x.textContent=totalUsers.toLocaleString('pt-MZ'));$$('[data-stat="requests"]').forEach(x=>x.textContent=totalReq.toLocaleString('pt-MZ'));$$('[data-stat="pickups"]').forEach(x=>x.textContent=totalPick.toLocaleString('pt-MZ'));}
function renderAll(){renderRequests();renderCitizen();renderRecycler();renderRewards();renderStats();}
$('#export-requests')?.addEventListener('click',()=>{const rows=state.requests.map(r=>[r.id,r.user,r.type,r.quantity,r.address,r.status,r.date,r.recycler||''].map(x=>`"${String(x).replaceAll('"','""')}"`).join(','));const blob=new Blob(['ID,Utilizador,Tipo,Quantidade,Endereco,Status,Data,Reciclador\n'+rows.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ecolink-solicitacoes.csv';a.click();URL.revokeObjectURL(url)});
document.addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(!b)return;if(session?.role!=='admin'){toast('Apenas o administrador pode criar registos.','error');return}const type=b.dataset.add;openModal('Novo registo',`<form id="quick-add-form" class="modal-form"><label>Nome<input id="quick-name" required></label><label>Telefone<input id="quick-phone" required placeholder="+258 84 123 4567"></label><label>Bairro/Zona<input id="quick-zone" value="Centro"></label><button class="btn btn-primary btn-full">Guardar ${esc(type)}</button></form>`);$('#quick-add-form').addEventListener('submit',ev=>{ev.preventDefault();const name=$('#quick-name').value.trim(),phone=$('#quick-phone').value.trim(),zone=$('#quick-zone').value.trim();if(type==='reciclador'){state.recyclers.push({id:'R'+Date.now(),name,phone,zone,status:'Online',collections:0})}else if(type==='utilizador'){state.users.push({id:'U'+Date.now(),name,phone,role:'municipe',points:0,status:'Ativo',bairro:zone})}else if(type==='ponto'){state.rewards.push({type:'Ponto de reciclagem',name,zone})}else if(type==='recolha'){state.requests.push({id:'#'+(1000+state.requests.length+1),user:'Administrador',type:'Agendada',quantity:'A definir',address:zone,note:'Agendada pelo administrador',date:new Date().toLocaleDateString('pt-MZ'),status:'Pendente',photos:[]})}save();$('#modal').classList.add('hidden');renderAll();toast('Registo guardado localmente.')})});
$('#save-settings')?.addEventListener('click',()=>toast('Configurações guardadas localmente.'));$('#generate-report')?.addEventListener('click',()=>toast('Relatório local gerado. Use Exportar para descarregar os dados.'));$('#period-select')?.addEventListener('change',e=>toast(`Período: ${e.target.value}`));
renderAll();
if('serviceWorker' in navigator && location.protocol!=='file:'){navigator.serviceWorker.register('sw.js').catch(()=>{})}
document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal').classList.add('hidden')});
